### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by kingnare** [chzuqi/WechatAne#2]
CCExtensionHandle.m 第124行中标题被写死了.

**Comment by chzuqi** [comment]
好，马上改

**Comment by kingnare** [comment]
:+1:

**Comment by stevenlew** [comment]
分享到朋友圈时"title"和“content"内容是一样的。

**Comment by chzuqi** [comment]
请问分享朋友圈用的是应用信息还是图片信息还是文字信息？

**Comment by stevenlew** [comment]
分享带图片信息的内容，用下面的方法分享时，title和content的内容是一样的，都是取的title变量的值。
WeixinSdk.instance.sendAppContent(WeixinSdk.WXSceneTimeline, title, content, "http://Url", bmpData);

**Comment by chzuqi** [comment]
这个应用信息貌似只有title有效，content不会显示的，点进去就跳进去链接了。

**Comment by benyme** [comment]
ANE_FUNCTION(wechat_function_app)
{
    return [CCext_handle sendAppContent:argv[0] title:argv[1] text:argv[1] url:argv[3] image:argv[4]];
}

@chzuqi 这个text参数可以改成argv[2]吗，现在title和content是一样的，看着好别扭，虽然在微信端点发送后不会显示出来，但是打开微信时，可以显示的吧？这个可以改一下吗，感谢！

**Comment by chzuqi** [comment]
好的，感谢您的提出，现已修复。我一直没注意到content的出现的地方，真失误。
